GET http://localhost:5000/navbar/0
###

POST http://localhost:5000/leads/new-lead
Content-Type: application/json

{
		"status": "lead lost",
		"statusDate": "2018-11-13",
		"referrer": "BDM Staff",
		"source": "App",
		"category": "Re-finance",
		"customerName": "Marguerite Parsons",
		"amount": "34264",
		"dateOfLead": "2018-11-03",
		"lender": "Virgin Money",
		"employee": "Johann"
}
###
GET http://localhost:5000/leads/select/1
###
PATCH http://localhost:5000/leads/52/edit
Content-Type: application/json

{
	"status":"approval"
}